services:
  db:
    container_name: fullcycle-docker-node-database
    build: ./database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 5s
      timeout: 10s
      retries: 3
  app:
    container_name: "fullcycle-docker-node-api"
    build: ./api
    volumes:
      - ./api:/app
    networks:
      - internal
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/ping"]
      start_period: 20s
      interval: 10s
      timeout: 1s
      retries: 3
  nginx:
    restart: always
    build: ./nginx
    depends_on:
      app:
        condition: service_healthy
    networks:
      - internal
    ports:
      - "8080:80"

networks:
  internal:
    driver: bridge

volumes:
  mysql_data:
    driver: local
